// ============================================================================
// Day 31: Freezed Models with JSON Serialization
// ============================================================================
// freezed: Generates immutable classes with copyWith, equality, toString
// json_serializable: Generates fromJson/toJson methods
//
// 🎯 BENEFITS:
// ✅ Immutable data classes (no accidental mutations)
// ✅ Auto-generated copyWith for easy updates
// ✅ Equality & hashCode based on fields
// ✅ toString() for debugging
// ✅ Type-safe JSON serialization
// ✅ Union types support (sealed classes)
//
// 🔧 ANNOTATIONS:
// @freezed - Main annotation for class generation
// @JsonSerializable() - Enables JSON serialization
// part 'models.freezed.dart' - Generated freezed code
// part 'models.g.dart' - Generated JSON code
//
// 🚀 GENERATION:
// Run: flutter pub run build_runner build --delete-conflicting-outputs
// ============================================================================

import 'package:freezed_annotation/freezed_annotation.dart';

// ============================================================
// CRITICAL: Part directives for code generation
// ============================================================
// These files will be generated by build_runner
// - .freezed.dart: Contains freezed generated code
// - .g.dart: Contains JSON serialization code
part 'models.freezed.dart';
part 'models.g.dart';

// ============================================================================
// Product Model - For cached_network_image demo
// ============================================================================
// Demonstrates:
// - Basic freezed model
// - JSON serialization with custom keys
// - DateTime handling
// - Nullable fields
// - Default values

@freezed
class Product with _$Product {
  // ============================================================
  // Factory constructor with named parameters
  // ============================================================
  // freezed generates:
  // - Private constructor
  // - copyWith method
  // - Equality operators
  // - toString method
  const factory Product({
    // Required fields
    required int id,
    required String title,
    required double price,
    
    // Optional fields with @Default for null safety
    @Default('') String description,
    @Default('') String category,
    @Default('') String imageUrl,
    
    // Field with custom JSON key mapping
    // API might use "created_at", we use createdAt in Dart
    DateTime? createdAt,
    
    // Nullable field
    int? stock,
  }) = _Product;

  // ============================================================
  // JSON Deserialization
  // ============================================================
  // fromJson factory - generated by json_serializable
  // Converts JSON map to Product instance
  factory Product.fromJson(Map<String, dynamic> json) =>
      _$ProductFromJson(json);
}

// ============================================================================
// Post Model - For user posts demo
// ============================================================================
// Simple model for blog posts or articles

@freezed
class Post with _$Post {
  const factory Post({
    required int id,
    required int userId,
    required String title,
    required String body,
  }) = _Post;

  factory Post.fromJson(Map<String, dynamic> json) => _$PostFromJson(json);
}

// ============================================================================
// User Model - For go_router parameters demo
// ============================================================================
// Demonstrates:
// - Complex nested objects
// - Enum in freezed
// - Custom JSON converters

@freezed
class User with _$User {
  const factory User({
    required int id,
    required String name,
    required String email,
    
    @Default('') String avatar,
    @Default(UserRole.user) UserRole role,
    
    // Nested object - Address
    Address? address,
    
    DateTime? registeredAt,
  }) = _User;

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
}

// ============================================================================
// Address Model - Nested object example
// ============================================================================

@freezed
class Address with _$Address {
  const factory Address({
    required String street,
    required String city,
    required String country,
    
    @Default('') String zipCode,
  }) = _Address;

  factory Address.fromJson(Map<String, dynamic> json) =>
      _$AddressFromJson(json);
}

// ============================================================================
// UserRole Enum - Type-safe role system
// ============================================================================
// freezed supports enums in models
// json_serializable can serialize/deserialize them

enum UserRole {
  @JsonValue('admin')
  admin,
  
  @JsonValue('moderator')
  moderator,
  
  @JsonValue('user')
  user,
  
  @JsonValue('guest')
  guest,
}

// ============================================================================
// Auth Token Model - For flutter_secure_storage demo
// ============================================================================
// Demonstrates:
// - Simple data transfer object
// - Token expiration handling
// - Computed properties (via extension)

@freezed
class AuthToken with _$AuthToken {
  const factory AuthToken({
    required String accessToken,
    required String refreshToken,
    required DateTime expiresAt,
    
    @Default('Bearer') String tokenType,
  }) = _AuthToken;

  factory AuthToken.fromJson(Map<String, dynamic> json) =>
      _$AuthTokenFromJson(json);
}

// ============================================================================
// Extension for computed properties
// ============================================================================
// freezed allows extensions for additional behavior

extension AuthTokenX on AuthToken {
  // Check if token is expired
  bool get isExpired => DateTime.now().isAfter(expiresAt);
  
  // Check if token expires soon (within 5 minutes)
  bool get expiresSoon {
    final fiveMinutesFromNow = DateTime.now().add(const Duration(minutes: 5));
    return expiresAt.isBefore(fiveMinutesFromNow);
  }
  
  // Get authorization header value
  String get authorizationHeader => '$tokenType $accessToken';
}

// ============================================================================
// USAGE EXAMPLES
// ============================================================================
/*

// 1. CREATE INSTANCE
final product = Product(
  id: 1,
  title: 'Laptop',
  price: 999.99,
  description: 'Gaming laptop',
  imageUrl: 'https://example.com/laptop.jpg',
);

// 2. COPY WITH MODIFICATIONS
final updatedProduct = product.copyWith(
  price: 899.99,
  stock: 10,
);

// 3. EQUALITY
print(product == updatedProduct); // false (price changed)

// 4. JSON SERIALIZATION
final json = product.toJson();
final fromJson = Product.fromJson(json);

// 5. PATTERN MATCHING (Union types)
// See ProductState below for union type example

*/

// ============================================================================
// Union Types (Sealed Classes) - Advanced freezed feature
// ============================================================================
// Represents different states of data loading
// Perfect for state management

@freezed
class ProductState with _$ProductState {
  const factory ProductState.initial() = _Initial;
  const factory ProductState.loading() = _Loading;
  const factory ProductState.success(List<Product> products) = _Success;
  const factory ProductState.error(String message) = _Error;
}

// Usage with pattern matching:
/*
productState.when(
  initial: () => Text('No data'),
  loading: () => CircularProgressIndicator(),
  success: (products) => ProductList(products),
  error: (msg) => ErrorWidget(msg),
);
*/
